---
- name: Deploy Spring Pet Clinic as a service
  hosts: all
  become: yes
  tasks:
    - name: Update Ubuntu packages and install open-JDK11
      apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present
    - name: Create a Spring pet Clinic Directory
      ansible.builtin.file:
        path: /usr/share/springpetclinic
        state: directory
    - name: Download SpringPet Clinic
      get_url:
        url:   https://referenceapplicationskhaja.s3-us-west-2.amazonaws.com/spring-petclinic-2.4.2.jar
        dest: /usr/share/springpetclinic/ 
    - name: Create a Springbootuser
      user:
        name: springbootuser
        password: springbootuser
        state: present
    - name: Change the ownership of Springboot
      file:
        path: /usr/share/springpetclinic/spring-petclinic-2.4.2.jar
        owner: springbootuser
        mode: '500'
        state: file
    - name: Copy the springpetclinic.service
      copy:
        dest: /etc/systemd/system/springpetclinic.service
        src: springpetclinic.service
    - name: Start springpetclinic.service
      systemd:
        name: springpetclinic.service
        enabled: yes
        state: started        
             
