---
- name: Deploy Spring Pet Clinic as a service
  hosts: all
  become: yes
  tasks:
    - name: Update Ubuntu packages and install open-JDK11
      apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present
    - name: Create a Spring pet Clinic Directory
      anisble.builtin.file:
        path: /usr/share/springpetclinic
        state: directory
    - name: Download SpringPet Clinic
      get_url:
        url:   https://referenceapplicationskhaja.s3-us-west-2.amazonaws.com/spring-petclinic-2.4.2.jar
        dest: /usr/share/springpetclinic/  
